stages:
  - mirror
  - release
  - docs
  - finalize

variables:
  GITLAB_ACCESS_TOKEN: "$GITLAB_ACCESS_TOKEN"
  GITHUB_ACCESS_TOKEN: "$GITHUB_ACCESS_TOKEN"

github_mirror:
  stage: mirror
  tags:
    - linux-buildserver
  script:
    - git checkout master
    - git pull
    - git push git@github.com:namboy94/android-dice.git master -f
    - git checkout develop
    - git pull
    - git push git@github.com:namboy94/android-dice.git develop -f

upload_gitlab_release:
  stage: release
  only:
    - master
  tags:
    - linux-buildserver
  script:
    - mkdir -p artifacts
    - git clone https://gitlab.namibsun.net/namboy94/gitlab-release-uploader.git
    - git clone https://gitlab.namibsun.net/namboy94/changelog-reader.git
    - python changelog-reader/changelog-reader.py -c CHANGELOG -d  current_changelog
    - python gitlab-release-uploader/gitlab-release-uploader.py namboy94 android-dice $GITLAB_ACCESS_TOKEN
      $(gradle version -q) current_changelog artifacts -b master -u https://gitlab.namibsun.net

upload_github_release:
  stage: release
  only:
    - master
  tags:
    - linux-buildserver
  script:
    - mkdir -p artifacts
    - git clone https://gitlab.namibsun.net/namboy94/github-release-uploader.git
    - git clone https://gitlab.namibsun.net/namboy94/changelog-reader.git
    - python changelog-reader/changelog-reader.py -c CHANGELOG -d current_changelog
    - python github-release-uploader/github-release-uploader.py namboy94 android-dice $GITHUB_ACCESS_TOKEN
      $(gradle version -q) current_changelog artifacts -b master

gitstats:
  stage: docs
  tags:
    - linux-buildserver
  only:
    - master
    - develop
  script:
    - gitstats . gitstats
    - rsync -av gitstats/ /var/www/gitstats.namibsun.net/public_html/gitstats/android-dice --delete-before
    - git_stats generate
    - rsync -av git_stats/ /var/www/gitstats.namibsun.net/public_html/git_stats/android-dice --delete-before

update_site_indexes:
  stage: finalize
  tags:
    - linux-buildserver
  script:
    - git clone https://gitlab.namibsun.net/namboy94/html-index-generator.git
    - cd html-index-generator
    - python html-index-generator.py /var/www/coverage.namibsun.net/public_html
      /var/www/coverage.namibsun.net/public_html/index.html
    - python html-index-generator.py /var/www/docs.namibsun.net/public_html
      /var/www/docs.namibsun.net/public_html/index.html
    - python html-index-generator.py /var/www/gitstats.namibsun.net/public_html
      /var/www/gitstats.namibsun.net/public_html/index.html
